
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/minlog_db
    username: minlog
    password: minlog1234
  servlet:
    multipart:
      location: c:\\portfolioFile
      maxFileSize: 200MB
      maxRequestSize: 100MB

  config:
    import: classpath:application-email.yml
    profiles:
      include:
        - email

# mybatis config
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 7070
